# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35c21bb0a92c9603548bef0af612e067517ef6d97cda00758356c0279491a7c8968c090ebe20c05c86b6d68df5e5ccd8a4a9e71622ec50ccb46e69847bd1059e

test:
  secret_key_base: 9f2afb4fab368125c6f74c70da7a9bd34f5578778c3cd60353e9ce8ca2a44dff6d7c2ca70ec2c418832e2132d785d5475ce201c47d91ee27e448d8932dded27c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
