require:
  - rubocop-thread_safety
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - custom_plan.rb
    - bin/*
    - templates/*
    - db/migrate/*
    - features/step_definitions/email_steps.rb
    - Guardfile
    - features/support/transforms.rb
    - vendor/*
    - !ruby/regexp /templates/
    - tmp/*
      spec/dummy/*
Documentation:
  Enabled: false
LeadingCommentSpace:
  Enabled: false
LineLength:
  Enabled: false
Lint/HandleExceptions:
  Enabled: true
  Exclude:
    - custom_plan.rb
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - Gemfile
    - spec/**/*
Metrics/LineLength:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ExpectActual:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false


