language: ruby
install:
  - bundle install --path vendor/bundle
  - npm install
rvm:
 - 2.4.2
  - 2.5.0
before_script:
  - bundle exec rake septimo:dummy_app
  - bundle exec rake septimo:dummy_engine
script: bundle exec rspec -f doc spec
